baseURL: mparvin.me
title: Madvin (Mohammad Parvin)
paginate: 5
theme: charlolamode



menu:
    main:
        - name: Contact
          url: contact/
          weight: 30
        - name: Articles
          url: articles/
          weight: 20
        # - name: Categories
        #   url: categories/
        #   weight: 10
        # - name: new Tab
        #   url: mewtab/
        #   weight: defines order of tabs


params:
    author: Madvin


    defaultTheme: auto
    disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    displayFullLangName: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true

    profileMode:
        enabled: true
        title: Mohammad Parvin
        imageUrl: "/images/profile.png"
        imageTitle: madvin image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: My Articles
              url: /articles/
    mainSections:
      - articles

    socialIcons:
        - name: buymeacoffee
          url: "https://buymeacoffee.com/mparvin"
        - name: github
          url: "https://github.com/mparvin"
        - name: linkedin
          url: "https://www.linkedin.com/in/mparvin/"
        - name: twitter
          url: "https://twitter.com/mad__vin"


    # change favicon in images folder (icon for web tab)
    assets:
          favicon: "/images/favicon.ico"
          favicon16x16: "/images/favicon-16x16.png"
          favicon32x32: "/images/favicon-32x32.png"
          apple_touch_icon: "/images/apple-touch-icon.png"
          safari_pinned_tab: "/images/apple-touch-icon.png"



enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

minify:
    disableXML: true

